# Generated by Django 4.0.6 on 2023-01-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=25, verbose_name='ad: ')),
                ('email', models.CharField(max_length=25, verbose_name='email: ')),
                ('movzu', models.CharField(max_length=15, verbose_name='movzu: ')),
                ('mesaj', models.CharField(max_length=165, verbose_name='mesaj: ')),
                ('cari_id', models.IntegerField(max_length=10, verbose_name='cari_xeber: ')),
                ('Tarix', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=25, verbose_name='ad: ')),
                ('email', models.CharField(max_length=25, verbose_name='email: ')),
                ('movzu', models.CharField(max_length=15, verbose_name='movzu: ')),
                ('mesaj', models.CharField(max_length=200, verbose_name='mesaj ')),
                ('Tarix', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50)),
                ('basliq', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=1000)),
                ('metn', models.CharField(max_length=1000)),
                ('kateqoriya', models.CharField(max_length=25)),
                ('tarix', models.CharField(max_length=25)),
            ],
        ),
    ]
